version: "3"
services:
  # hardware emulation starts a server for you on port 9292
  emulator:
    image: csiot/emulator
    build: ./emulator
    ports: 
      - '9292:9292'
    volumes: 
      - ./emulator-config.yaml:/emulator/config.yaml

  motion_sensor:
    image: csiot/bridge
    build: ./aws
    volumes:
      - "./certs/motion:/app/certs/client:ro"
      - "./certs/root-CA.crt:/app/certs/root-CA.crt:ro"
    depends_on:
      - emulator
    env_file: ./aws/.env      
    environment:
      # override setting from .env file since we can reach the container under its name, not via localhost
      - DEVICE_ENDPOINT=http://emulator:9292/gpios/motion_sensor
      - AWS_THING_NAME=motion

  door_lock:
    image: csiot/bridge
    build: ./aws
    volumes:
      - "./certs/door_lock:/app/certs/client:ro"
      - "./certs/root-CA.crt:/app/certs/root-CA.crt:ro"
    depends_on:
      - emulator
    env_file: ./aws/.env      
    environment:
      # override setting from .env file since we can reach the container under its name, not via localhost
      - DEVICE_ENDPOINT=http://emulator:9292/gpios/door_lock
      - AWS_THING_NAME=door_lock

  alarm:
    image: csiot/bridge
    build: ./aws
    volumes:
      - "./certs/alarm:/app/certs/client:ro"
      - "./certs/root-CA.crt:/app/certs/root-CA.crt:ro"
    depends_on:
      - emulator
    env_file: ./aws/.env
    environment:
      # override setting from .env file since we can reach the container under its name, not via localhost
      - DEVICE_ENDPOINT=http://emulator:9292/gpios/alarm
      - AWS_THING_NAME=alarm

  temp_sensor:
    image: csiot/bridge
    build: ./aws
    volumes:
      - "./certs/temperature:/app/certs/client:ro"
      - "./certs/root-CA.crt:/app/certs/root-CA.crt:ro"
    depends_on:
      - emulator
    env_file: ./aws/.env      
    environment:
      # override setting from .env file since we can reach the container under its name, not via localhost
      - DEVICE_ENDPOINT=http://emulator:9292/gpios/temp_sensor
      - AWS_THING_NAME=temp_sensor

  fan:
    image: csiot/bridge
    build: ./aws
    volumes:
      - "./certs/fan:/app/certs/client:ro"
      - "./certs/root-CA.crt:/app/certs/root-CA.crt:ro"
    depends_on:
      - emulator
    env_file: ./aws/.env      
    environment:
      # override setting from .env file since we can reach the container under its name, not via localhost
      - DEVICE_ENDPOINT=http://emulator:9292/gpios/fan
      - AWS_THING_NAME=fan

  humidity_sensor:
    image: csiot/bridge
    build: ./aws
    volumes:
      - "./certs/humidity:/app/certs/client:ro"
      - "./certs/root-CA.crt:/app/certs/root-CA.crt:ro"
    depends_on:
      - emulator
    env_file: ./aws/.env      
    environment:
      # override setting from .env file since we can reach the container under its name, not via localhost
      - DEVICE_ENDPOINT=http://emulator:9292/gpios/humidity_sensor
      - AWS_THING_NAME=humidity_sensor

  humidifier:
    image: csiot/bridge
    build: ./aws
    volumes:
      - "./certs/humidifier:/app/certs/client:ro"
      - "./certs/root-CA.crt:/app/certs/root-CA.crt:ro"
    depends_on:
      - emulator
    env_file: ./aws/.env      
    environment:
      # override setting from .env file since we can reach the container under its name, not via localhost
      - DEVICE_ENDPOINT=http://emulator:9292/gpios/humidifier
      - AWS_THING_NAME=humidifier  
      
  heating:
    image: csiot/bridge
    build: ./aws
    volumes:
      - "./certs/heating:/app/certs/client:ro"
      - "./certs/root-CA.crt:/app/certs/root-CA.crt:ro"
    depends_on:
      - emulator
    env_file: ./aws/.env      
    environment:
      # override setting from .env file since we can reach the container under its name, not via localhost
      - DEVICE_ENDPOINT=http://emulator:9292/gpios/heating
      - AWS_THING_NAME=heating